### ISSUE TITLE
FAQ unclear

### ISSUE THREAD

**Issue by EmmaRenauld** [imeka/mi-brain#3]
In the FAQ, installation under linux, it is suggested to do: "extract the .tar.gz release archive and execute installer.sh".  I can't see any installer.sh. Extracted archive (MI-Brain-2020.04.09_r2e0ff5-linux-x86_64) contains bin, licence and MI-Brain.sh.

**Comment by nilgoyette** [comment]
Right, thank you. It's fixed now.
